---
- name: Github API Request to Get Runner Token
  hosts: localhost
  vars_files:
    - vault.yml
  tasks:
    - name: Get GitHub Actions runner registration token
      ansible.builtin.uri:
        url: "https://api.github.com/repos/{{ github_owner }}/{{ github_repo }}/actions/runners/registration-token"
        method: POST
        headers:
          Accept: "application/vnd.github+json"
          Authorization: "Bearer {{ github_api_key }}"
          X-GitHub-Api-Version: "2022-11-28"
        status_code: 201
      register: runner_token_response

    - name: Extract registration token
      ansible.builtin.set_fact:
        registration_token: "{{ runner_token_response.json | json_query('token') }}"

- name: Download Github Runner Binary, Install, and Connect to Github
  hosts: runner
  vars_files:
    - vault.yml
  tasks:
    - name: Create actions-runner folder
      ansible.windows.win_file:
        path: C:\actions-runner
        state: directory

    - name: Download GitHub Actions runner package
      ansible.windows.win_get_url:
        url: https://github.com/actions/runner/releases/download/v2.320.1/actions-runner-win-x64-2.320.1.zip
        dest: C:\actions-runner\actions-runner-win-x64-2.320.1.zip

    - name: Extract the runner package
      community.windows.win_unzip:
        src: C:\actions-runner\actions-runner-win-x64-2.320.1.zip
        dest: C:\actions-runner
        delete_archive: true

    - name: Run Github Runner Config with Registration Token
      ansible.windows.win_command:
        argv:
          - config.cmd
          - --unattended
          - --runasservice
          - --url
          - "https://github.com/{{ github_owner }}/{{ github_repo }}"
          - --token
          - "{{ hostvars.localhost.registration_token }}"
      args:
        chdir: C:\actions-runner
